name: CI/CD Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install sshpass -y
          
      - name: Deploy to server
        run: |
          sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            mkdir -p /root/projects/test_deployment
            cd /root/projects/test_deployment
            git pull https://github.com/farzot/deployment_test.git
            npm install
            npm run build
            pm2 reload test_deployment || pm2 start dist/main.js --name "test_deployment"
            pm2 save
          EOF

