name: CI/CD Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install sshpass -y
          
      - name: Deploy to server
        run: |
          sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            # Katalog mavjudligini tekshirish va kerak bo'lsa yaratish
            if [ ! -d "/root/projects/test_deployment" ]; then
              mkdir -p /root/projects/test_deployment
              git clone https://github.com/farzot/deployment_test.git /root/projects/test_deployment
            fi

            cd /root/projects/test_deployment

            # Git repositorydan kodni yangilash
            if [ -d ".git" ]; then
              git pull
            fi

            # package.json borligini tekshirish
            if [ -f "package.json" ]; then
              npm install
              npm run build
            else
              echo "package.json topilmadi!"
              exit 1
            fi

            # PM2 ni o'rnatish va ishga tushirish
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            pm2 reload test_deployment || pm2 start dist/main.js --name "test_deployment"
            pm2 save
          EOF
