name: CI and Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (local runner)
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'

    - name: Install dependencies (local runner)
      run: npm install

    - name: Build project (local runner)
      run: npm run build

    - name: Deploy to development server
      if: github.ref == 'refs/heads/master'
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
          # NVM o'rnatilganligini tekshirish va kerakli Node.js versiyasini tanlash
          if [ ! -d "$HOME/.nvm" ]; then
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
            source ~/.nvm/nvm.sh
          else
            source ~/.nvm/nvm.sh
          fi
          nvm install 20.10.0
          nvm use 20.10.0
          
          # PM2 o'rnatilganligini tekshirish
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi
          
          # Loyihaning joylashuvini yaratish va loyihani olish
          mkdir -p /root/projects/ci_cd_dep_test
          cd /root/projects/ci_cd_dep_test
          if [ ! -d ".git" ]; then
              git clone https://github.com/farzot/deployment_test.git .
          fi
          git pull origin master

          # Kerakli kutubxonalarni o'rnatish va loyihani build qilish
          npm install
          npm run build
          
          # PM2 orqali jarayonlarni boshqarish
          pm2 restart ci_cd_test || pm2 start npm --name="ci_cd_test" -- run start
          pm2 save
        EOF
